const NAME_REPLACEMENTS = [
  [/\bCha\b/g, "Chá"],
  [/\bArnica\b/g, "Arnica"],
  [/\bBarbatimao\b/g, "Barbatimão"],
  [/\bArtemisia\b/g, "Artemísia"],
  [/\bChapeu\b/g, "Chapéu"],
  [/\bLeao\b/g, "Leão"],
  [/\bSao\b/g, "São"],
  [/\bHibisco Po\b/g, "Hibisco Pó"],
  [/\bHortela\b/g, "Hortelã"],
  [/\bIpe\b/g, "Ipê"],
  [/\bLimao\b/g, "Limão"],
  [/\bMaracuja\b/g, "Maracujá"],
  [/\bSalvia\b/g, "Sálvia"],
  [/\bPicao\b/g, "Picão"],
  [/\bMacela Grao\b/g, "Macela Grão"],
  [/\bGrao\b/g, "Grão"],
  [/\bAcai\b/g, "Açaí"],
  [/\bProteina\b/g, "Proteína"],
  [/\bAmendoa\b/g, "Amêndoa"],
  [/\bAvela\b/g, "Avelã"],
  [/\bJapones\b/g, "Japonês"],
  [/\bDo Para\b/g, "do Pará"],
  [/\bNoz Macadamia\b/g, "Noz Macadâmia"],
  [/\bPecan\b/g, "Pecã"],
  [/\bAcafrao\b/g, "Açafrão"],
  [/\bAcucar\b/g, "Açúcar"],
  [/\bMaca\b/g, "Maca"],
  [/\bCanela Em Po\b/g, "Canela em pó"],
  [/\bCebola Em Po\b/g, "Cebola em pó"],
  [/\bCravo Em Po\b/g, "Cravo em pó"],
  [/\bFumaca Em Po\b/g, "Fumaça em pó"],
  [/\bNoz Moscada\b/g, "Noz-moscada"],
  [/\bPaprica\b/g, "Páprica"],
  [/\bCamarao\b/g, "Camarão"],
  [/\bMaranh?ao\b/g, "Maranhão"],
  [/\bLinhaca\b/g, "Linhaça"],
  [/\bMarron\b/g, "Marrom"],
  [/\bGlutem\b/g, "Glúten"],
  [/\bSoja Grauda\b/g, "Soja graúda"],
  [/\bEm Po\b/g, "Em Pó"],
  [/\b Po\b/g, " Pó"],
];

const normalizeNamePtBr = (name) => {
  let normalized = name;
  for (const [pattern, replacement] of NAME_REPLACEMENTS) {
    normalized = normalized.replace(pattern, replacement);
  }
  return normalized;
};

const p = (name, code, category) => ({
  name: normalizeNamePtBr(name),
  code,
  quantity: 0,
  category,
});

export const DEFAULT_PRODUCTS = [
  // Chás
  p("Cha Alcachofra", "19", "Chás"),
  p("Cha De Arnica", "264", "Chás"),
  p("Cha Alecrim Desidratado", "167", "Chás"),
  p("Cha Amora", "17", "Chás"),
  p("Cha Anis Estrelado", "18", "Chás"),
  p("Cha Assa Peixe", "113", "Chás"),
  p("Cha Barbatimao", "114", "Chás"),
  p("Cha Boldo", "96", "Chás"),
  p("Cha De Artemisia", "286", "Chás"),
  p("Cha De Valeriana", "285", "Chás"),
  p("Cha Camomila", "20", "Chás"),
  p("Cha Cana Do Brejo", "115", "Chás"),
  p("Cha Canela De Velho", "105", "Chás"),
  p("Cha Canela Em Pau / Inteira", "261", "Chás"),
  p("Cha Capim Santo", "236", "Chás"),
  p("Cha Carqueja", "116", "Chás"),
  p("Cha Cavalinha", "21", "Chás"),
  p("Cha Chapeu De Couro", "132", "Chás"),
  p("Cha Dente Leao", "110", "Chás"),
  p("Cha Desincha Dia", "250", "Chás"),
  p("Cha Endro", "186", "Chás"),
  p("Cha Erva Cidreira", "22", "Chás"),
  p("Cha Erva Doce", "163", "Chás"),
  p("Cha Erva Sao Joao", "134", "Chás"),
  p("Cha Espinheira Santa", "24", "Chás"),
  p("Cha Funcho", "244", "Chás"),
  p("Cha Graviola", "246", "Chás"),
  p("Cha Guaco", "25", "Chás"),
  p("Cha Hibisco Flores", "26", "Chás"),
  p("Cha Hibisco Po", "120", "Chás"),
  p("Cha Hortela", "27", "Chás"),
  p("Cha Ipe Roxo", "121", "Chás"),
  p("Cha Louro Folha", "262", "Chás"),
  p("Cha De Limao Desidratado", "354", "Chás"),
  p("Cha De Laranja Desidratado", "346", "Chás"),
  p("Cha Maracuja", "6", "Chás"),
  p("Cha Melissa", "135", "Chás"),
  p("Cha Moringa Folha", "129", "Chás"),
  p("Cha Mulungu", "241", "Chás"),
  p("Cha Oliveira", "28", "Chás"),
  p("Cha Ora Pronabis", "247", "Chás"),
  p("Cha Pata Vaca", "138", "Chás"),
  p("Cha Preto", "242", "Chás"),
  p("Cha Quebra Pedra", "29", "Chás"),
  p("Cha Salvia", "171", "Chás"),
  p("Cha Senne", "95", "Chás"),
  p("Cha Tanchagem", "249", "Chás"),
  p("Cha De Eucalipto", "307", "Chás"),
  p("Cha Unha Gato", "109", "Chás"),
  p("Cha Uxi Amarelo", "125", "Chás"),
  p("Cha Verde", "30", "Chás"),
  p("Cha De Macela Grao", "339", "Chás"),
  p("Cha De Erva Baleeira", "368", "Chás"),
  p("Cha De Arruda", "409", "Chás"),
  p("Cha De Alfavaca", "410", "Chás"),
  p("Cha De Alfazema", "422", "Chás"),
  p("Cha Mix Calmante", "395", "Chás"),
  p("Cha Picao Preto", "396", "Chás"),
  p("Semente De Sucupira", "195", "Chás"),
  p("Cha De Quebra Pedra", "460", "Chás"),
  p("Cha De Insulina", "361", "Chás"),
  p("Cha De Alecrim", "279", "Chás"),
  p("Cha Seca Barriga", "251", "Chás"),
  p("Cha De Lavanda", "422B", "Chás"),
  p("Cha De Aroeira", "469", "Chás"),

  // Suplementos
  p("Bcaa", "172", "Suplementos"),
  p("Arginina", "466", "Suplementos"),
  p("Beta Alanina", "245", "Suplementos"),
  p("Creatina", "33", "Suplementos"),
  p("L Glutamina", "51", "Suplementos"),
  p("Maca Vermelha", "349", "Suplementos"),
  p("Maca Peruana Ultra", "52", "Suplementos"),
  p("Maca Peruana Black", "348", "Suplementos"),
  p("Maltodextrina", "56", "Suplementos"),
  p("Tribulos", "152", "Suplementos"),
  p("Taurina", "462", "Suplementos"),
  p("Whey Natural", "415", "Suplementos"),
  p("Whey Baunilha", "224", "Suplementos"),
  p("Whey Morango", "223", "Suplementos"),
  p("Whey Chocolate", "222", "Suplementos"),
  p("Whey Cookies", "389", "Suplementos"),
  p("Proteina Isolada De Soja", "181", "Suplementos"),
  p("Proteina De Arroz", "256", "Suplementos"),
  p("Proteina De Ervilha", "304", "Suplementos"),
  p("Creatina Monohidratada", "CRE001", "Suplementos"),
  p("Whey Protein Chocolate", "WHE001", "Suplementos"),
  p("Spirulina Em Po", "SPI001", "Suplementos"),

  // Grãos, sementes, oleaginosas, frutas, farinaceos, lanches e soja
  p("Amendoa Crua", "5", "Grãos"),
  p("Amendoa Laminada", "187", "Grãos"),
  p("Amendoim Salgado", "197", "Grãos"),
  p("Amendoim Polvilho", "433", "Grãos"),
  p("Amendoim Com Salsa E Cebola", "325", "Grãos"),
  p("Amendoim Japones Tradicional", "449", "Grãos"),
  p("Amendoim Mostarda E Mel", "450", "Grãos"),
  p("Amendoim Picante", "357", "Grãos"),
  p("Amendoim Gralado", "219", "Grãos"),
  p("Amendoim S/ Pele", "7", "Grãos"),
  p("Amendoim Paçoca", "196", "Grãos"),
  p("Avela", "144", "Grãos"),
  p("Castanha Caju Banda", "122", "Grãos"),
  p("Castanha Caju Inteira", "14", "Grãos"),
  p("Castanha De Caju Granulada", "190", "Grãos"),
  p("Castanha Do Para", "16", "Grãos"),
  p("Mix Nuts", "199", "Grãos"),
  p("Noz Macadamia", "154", "Grãos"),
  p("Pecan", "225", "Grãos"),
  p("Nozes Chilena Inteira", "58", "Grãos"),
  p("Nozes Chilena Granulado", "376", "Grãos"),
  p("Pistache Com Casca", "59", "Grãos"),
  p("Amaranto Flocos", "37", "Grãos"),
  p("Amaranto Grao", "3", "Grãos"),
  p("Arroz Integral Grao", "9", "Grãos"),
  p("Ervilha Inteira", "107", "Grãos"),
  p("Feijao Azuki", "74", "Grãos"),
  p("Feijao Moyashi", "269", "Grãos"),
  p("Feno Grego", "118", "Grãos"),
  p("Gergelim Branco", "15", "Grãos"),
  p("Gergelim Integral", "78", "Grãos"),
  p("Gergelim Preto", "45", "Grãos"),
  p("Grao De Bico", "75", "Grãos"),
  p("Lentilha", "79", "Grãos"),
  p("Lentilha Vermelha", "306", "Grãos"),
  p("Mix De Sementes", "461", "Grãos"),
  p("Mostarda Grao", "260", "Grãos"),
  p("Mostarda Em Po", "308", "Grãos"),
  p("Milho De Pipoca", "455", "Grãos"),
  p("Quinoa Flocos", "61", "Grãos"),
  p("Quinoa Grao Branca", "83", "Grãos"),
  p("Quinoa Mix", "182", "Grãos"),
  p("Semente Abobora Sem Casca", "155", "Grãos"),
  p("Semente De Chia", "064", "Grãos"),
  p("Semente De Moringa", "329", "Grãos"),
  p("Semente De Linhaca Dourada", "065", "Grãos"),
  p("Semente De Linhaca Marron", "161", "Grãos"),
  p("Semente Girassol S/Casca", "089", "Grãos"),
  p("Soja Grao", "185", "Grãos"),
  p("Trigo Grao", "143", "Grãos"),
  p("Painco Grao", "452", "Grãos"),
  p("Mix De Frutas Vermelhas", "314", "Grãos"),
  p("Ameixa Sem Caroco", "4", "Grãos"),
  p("Banana Chips Salgada", "146", "Grãos"),
  p("Banana Cristal", "164", "Grãos"),
  p("Banana Passa", "13", "Grãos"),
  p("Blueberry", "047", "Grãos"),
  p("Coco Chips", "158", "Grãos"),
  p("Coco Flocos", "8", "Grãos"),
  p("Coco Ralado", "217", "Grãos"),
  p("Coco Caramelizado", "446", "Grãos"),
  p("Cereja", "383", "Grãos"),
  p("Cranberry", "32", "Grãos"),
  p("Damasco", "100", "Grãos"),
  p("Frutas Cristalizadas", "128", "Grãos"),
  p("Gojiberry", "046", "Grãos"),
  p("Laranja Cristalizada", "149", "Grãos"),
  p("Limao Cristalizado", "150", "Grãos"),
  p("Mix De Frutas", "202", "Grãos"),
  p("Mix De Frutas Tropical", "69", "Grãos"),
  p("Morango Desidratado", "218", "Grãos"),
  p("Tamara Sem Caroco", "067", "Grãos"),
  p("Tamara Jumbo", "386", "Grãos"),
  p("Uva Passa Branca", "165", "Grãos"),
  p("Uva Passa Preta", "068", "Grãos"),
  p("Kiwi", "77", "Grãos"),
  p("Agar Agar", "043", "Grãos"),
  p("Acai Po", "336", "Grãos"),
  p("Polvilho Doce", "66", "Grãos"),
  p("Polvilho Azedo", "84", "Grãos"),
  p("Psyllium Husk", "153", "Grãos"),
  p("Spirulina", "73", "Grãos"),
  p("Bala De Colagen", "12", "Grãos"),
  p("Bolo De Banana", "300", "Grãos"),
  p("Bolo De Maca", "299", "Grãos"),
  p("Bala Banana Coco", "406", "Grãos"),
  p("Biscoito De Arroz Most/Mel", "493", "Grãos"),
  p("Biscoito De Arroz Barbecue", "87", "Grãos"),
  p("Biscoito De Arroz Cebola E Salsa", "381", "Grãos"),
  p("Biscoito De Arroz Queijo", "108", "Grãos"),
  p("Biscoito De Avela", "352", "Grãos"),
  p("Biscoito Amendoim", "357B", "Grãos"),
  p("Biscoito Lemon", "418", "Grãos"),
  p("Biscoito Acafrao", "419", "Grãos"),
  p("Biscoito Alho", "420", "Grãos"),
  p("Biscoito Beterraba", "421", "Grãos"),
  p("Biscoito Linhaca Com Ervas Finas", "473", "Grãos"),
  p("Biscoito Limao Com Pimenta", "475", "Grãos"),
  p("Biscoito Nutella", "476", "Grãos"),
  p("Biscoito Canela", "488", "Grãos"),
  p("Biscoito De Linhaca Com Acafrao", "474", "Grãos"),
  p("Biscoito Bombom", "482", "Grãos"),
  p("Biscoito Pistache", "483", "Grãos"),
  p("Beliscao De Goiaba", "484", "Grãos"),
  p("Beijinho De Freira", "485", "Grãos"),
  p("Biscoito Amendoim Chocolate", "486", "Grãos"),
  p("Biscoito De Polvilho", "487", "Grãos"),
  p("Canudo Doce De Leite", "448", "Grãos"),
  p("Cereal Mascavo", "414", "Grãos"),
  p("Cereal De Frutas", "200", "Grãos"),
  p("Cereal Choco Bola", "31", "Grãos"),
  p("Cereal De Arroz", "275", "Grãos"),
  p("Cereal Flakes Doce", "311", "Grãos"),
  p("Cereal Zero Acucar Milho", "273", "Grãos"),
  p("Chips De Batata Doce", "296", "Grãos"),
  p("Chips De Batata Sabor Queijo", "160", "Grãos"),
  p("Chips De Batata Churrasco", "377", "Grãos"),
  p("Chips De Batata Cebola E Salsa", "378", "Grãos"),
  p("Chip De Mandioca Barbecue", "387", "Grãos"),
  p("Doce De Leite Tradicional", "267", "Grãos"),
  p("Doce De Leite Com Coco", "472", "Grãos"),
  p("Chip De Mandioquinha", "333", "Grãos"),
  p("Gengibre Cristal", "413", "Grãos"),
  p("Granola Sem Glutem", "456", "Grãos"),
  p("Granola Diet Zero Acucar", "48", "Grãos"),
  p("Granola Mix 30", "49", "Grãos"),
  p("Granola 32 Ingredientes", "370", "Grãos"),
  p("Granola Cacau", "214", "Grãos"),
  p("Granola Acai", "233", "Grãos"),
  p("Granola Banana", "407", "Grãos"),
  p("Mix De Vegetais", "417", "Grãos"),
  p("Milho Mostarda E Mel", "141", "Grãos"),
  p("Nibs De Cacau", "169", "Grãos"),
  p("Rapadura", "206", "Grãos"),
  p("Rosquinha De Nata", "477", "Grãos"),
  p("Rosquinha De Cebola", "478", "Grãos"),
  p("Rosquinha Duo", "481", "Grãos"),
  p("Torradinha De Alho", "479", "Grãos"),
  p("Torradinha De Cebola", "480", "Grãos"),
  p("Zimbro", "353", "Grãos"),
  p("Tapioca Granulado", "204", "Grãos"),
  p("Shitake", "258", "Grãos"),
  p("Soja Bife", "177", "Grãos"),
  p("Soja Granulada", "292", "Grãos"),
  p("Soja Granulada Com Bacon", "175", "Grãos"),
  p("Soja Grauda", "291", "Grãos"),
  p("Soja Picanha", "371", "Grãos"),
  p("Soja Frango", "400", "Grãos"),
  p("Soja Cebola E Salsa", "379", "Grãos"),
  p("Soja Calabresa", "494", "Grãos"),

  // Temperos e condimentos
  p("Acafrao Caseiro", "287", "Temperos"),
  p("Ashwagandha", "439", "Temperos"),
  p("Acucar De Coco", "112", "Temperos"),
  p("Acucar Demerara", "1", "Temperos"),
  p("Acucar Mascavo", "2", "Temperos"),
  p("Alho Granulado", "277", "Temperos"),
  p("Alho Em Po", "170", "Temperos"),
  p("Alho Frito", "235", "Temperos"),
  p("Alho Cebola E Salsa", "289", "Temperos"),
  p("Ana Maria", "86", "Temperos"),
  p("Amaciante De Carne", "211", "Temperos"),
  p("Dry Rub Frango", "437", "Temperos"),
  p("Cenoura Em Flocos", "491", "Temperos"),
  p("Cebola Crisp", "411", "Temperos"),
  p("Curcuma Pura", "102", "Temperos"),
  p("Cominho Em Po", "297", "Temperos"),
  p("Coentro Em Po", "327", "Temperos"),
  p("Cacau Black", "366", "Temperos"),
  p("Cacau 100%", "71", "Temperos"),
  p("Cacau 70%", "385", "Temperos"),
  p("Cacau 50%", "188", "Temperos"),
  p("Cacau 32%", "471", "Temperos"),
  p("Gotas De Chocolate Branco", "330", "Temperos"),
  p("Gotas De Cacau 50%", "372", "Temperos"),
  p("Gotas Chocolate 73%", "380", "Temperos"),
  p("Gotas Ao Leite", "54", "Temperos"),
  p("Caldo De Bacon", "281", "Temperos"),
  p("Caldo De Carne", "191", "Temperos"),
  p("Caldo De Galinha", "271", "Temperos"),
  p("Caldo De Legumes", "104", "Temperos"),
  p("Caldo De Camarao", "365", "Temperos"),
  p("Canela Em Po", "103", "Temperos"),
  p("Cebola Em Po", "147", "Temperos"),
  p("Creme De Cebola", "212", "Temperos"),
  p("Cebola Flocos", "139", "Temperos"),
  p("Colorau", "305", "Temperos"),
  p("Chimichurri C/Pimenta", "210", "Temperos"),
  p("Chimichurri Barbecue", "265", "Temperos"),
  p("Chimichurri Com Limao", "254", "Temperos"),
  p("Chimichurri S/Pimenta", "180", "Temperos"),
  p("Cravo Da India Inteiro", "278", "Temperos"),
  p("Cravo Em Po", "133", "Temperos"),
  p("Curry", "53", "Temperos"),
  p("Edu Guedes", "215", "Temperos"),
  p("Eritritol", "178", "Temperos"),
  p("Ervas Finas", "131", "Temperos"),
  p("Fit Completo", "294", "Temperos"),
  p("Fit Frango", "295", "Temperos"),
  p("Flor De Sal", "234", "Temperos"),
  p("Fumaca Em Po", "216", "Temperos"),
  p("Glucomanana", "465", "Temperos"),
  p("Gengibre", "044", "Temperos"),
  p("Goma Xantana", "119", "Temperos"),
  p("Lemon Pepper", "82", "Temperos"),
  p("Manjericao", "183", "Temperos"),
  p("Manjerona", "331", "Temperos"),
  p("Noz Moscada", "201", "Temperos"),
  p("Oregano", "63", "Temperos"),
  p("Paprica Defumada", "272", "Temperos"),
  p("Paprica Doce", "136", "Temperos"),
  p("Paprica Picante", "137", "Temperos"),
  p("Pimenta Calabresa", "123", "Temperos"),
  p("Pimenta Cayena", "124", "Temperos"),
  p("Pimenta Preta", "276", "Temperos"),
  p("Pimenta Branca Po", "127", "Temperos"),
  p("Pimenta Rosa", "310", "Temperos"),
  p("Pimenta Preta Grao", "393", "Temperos"),
  p("Sal Marinho Mais Barato", "62", "Temperos"),
  p("Sal Marinho Mais Caro", "356", "Temperos"),
  p("Sal Rosa Fino", "70", "Temperos"),
  p("Salsa", "253", "Temperos"),
  p("Sal Parrilha Defumado", "320", "Temperos"),
  p("Stevia", "464", "Temperos"),
  p("Sucralose", "441", "Temperos"),
  p("Tempero Bife", "248", "Temperos"),
  p("Tempero Do Chef", "463", "Temperos"),
  p("Tempero Tartaro", "230", "Temperos"),
  p("Tempero Baiano", "205", "Temperos"),
  p("Tempero Caipira", "326", "Temperos"),
  p("Tempero Completo", "55", "Temperos"),
  p("Tempero Da Fazenda", "440", "Temperos"),
  p("Tempero Tudo", "438", "Temperos"),
  p("Tempero Para Feijao", "257", "Temperos"),
  p("Tempero Para Arroz", "338", "Temperos"),
  p("Tempero Pega Esposa", "399", "Temperos"),
  p("Tempero Pega Marido", "382", "Temperos"),
  p("Tempero Nordestino", "335", "Temperos"),
  p("Tempero Mineiro", "332", "Temperos"),
  p("Tempero Completo Curry", "252", "Temperos"),
  p("Tempero Para Peixe", "397", "Temperos"),
  p("Tempero Completo Carne", "161B", "Temperos"),
  p("Orange Pepper", "443", "Temperos"),
  p("Tomilho", "140", "Temperos"),
  p("Vinagrete Flocos", "176", "Temperos"),
  p("Xylitol", "173", "Temperos"),

  // Outros
  p("Argila Branca", "90", "Outros"),
  p("Argila Preta", "91", "Outros"),
  p("Argila Rosa", "284", "Outros"),
  p("Argila Verde", "101", "Outros"),
];
